create database domosys;
use domosys;

create table cliente  (
   ID_CLIENTE			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   RUT					VARCHAR(10) NOT NULL,
   NOMBRES				VARCHAR(150) NOT NULL,
   APE_PATERNO			VARCHAR(150) NOT NULL,
   APE_MATERNO			VARCHAR(150) NOT NULL,
   FECHA_NAC			DATE NOT NULL,	
   GENERO				VARCHAR(1) NOT NULL,	
   COMUNA				VARCHAR(100) NOT NULL,
   CALLE				VARCHAR(300) NOT NULL,
   FONO_MOVIL			VARCHAR(8) NOT NULL, 
   FONO_FIJO			VARCHAR(8),
   EMAIL				VARCHAR(200) NOT NULL,
   USER_CLIE			VARCHAR(20) NOT NULL,
   PASS_CLIE			VARCHAR(20) NOT NULL
) ENGINE = INNODB;

create table audit_cliente  (
   ID_REG_CLIE			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_CLIE				INTEGER NOT NULL,
   COMENTARIO_CLIE		VARCHAR(500) NOT NULL,
   FECH_HOR_CLIE		DATETIME NOT NULL
) ENGINE = INNODB;

create table raspberry  (
   ID_RASPBERRY			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_CLIEN				INTEGER NOT NULL,
   NUM_SERIE_RASP		VARCHAR(20) NOT NULL,
   MAC_RASP				VARCHAR(17) NOT NULL,
   ETHERNET				TINYINT(1) NOT NULL,
   WIFI					TINYINT(1) NOT NULL
) ENGINE = INNODB;

create table audit_raspberry (
   ID_REG_RASP			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_RASP				INTEGER NOT NULL,
   COMENTARIO_RASP		VARCHAR(500) NOT NULL,
   FECH_HOR_RASP		DATETIME NOT NULL
) ENGINE = INNODB;

create table arduino  (
   ID_ARDUINO			INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_RASPBE			INTEGER NOT NULL,
   NOMBRE_ARD			VARCHAR(200) NOT NULL,
   NUM_SERIE_ARD		VARCHAR(10) NOT NULL,
   PUERTO_COM			VARCHAR(6) NOT NULL
) ENGINE = INNODB;

create table componente  (
   ID_COMPONENTE		INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_ARD				INTEGER NOT NULL,
   PIN_ARD				INTEGER NOT NULL,
   TIPO_COMP			TINYINT(1) NOT NULL,	
   NOMBRE_COMP			VARCHAR(200) NOT NULL	
) ENGINE = INNODB;

create table uso  (
   ID_USO				INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_COMP				INTEGER NOT NULL,   
   ESTADO				TINYINT(1) NOT NULL,
   COMENTARIO_USO		VARCHAR(500),
   FECH_HOR_INI			DATETIME,
   FECH_HOR_FIN			DATETIME
) ENGINE = INNODB;


create table contacto  (
   ID_COMENTARIO		INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ID_USER				INTEGER NOT NULL,
   COMENTARIO_CONTACTO	VARCHAR(700) NOT NULL,
   FECH_HOR_CONTACTO	DATETIME NOT NULL
) ENGINE = INNODB;


ALTER TABLE cliente ADD CONSTRAINT UN_rut UNIQUE (RUT);
ALTER TABLE cliente ADD CONSTRAINT UN_email UNIQUE (EMAIL);
ALTER TABLE cliente ADD CONSTRAINT UN_user_clie UNIQUE (USER_CLIE);

ALTER TABLE raspberry ADD CONSTRAINT UN_mac_rasp UNIQUE (MAC_RASP);
ALTER TABLE raspberry ADD CONSTRAINT UN_num_serie_rasp UNIQUE (NUM_SERIE_RASP);

ALTER TABLE arduino ADD CONSTRAINT UN_num_serie_ard UNIQUE (NUM_SERIE_ARD);

 
alter table raspberry add constraint FK_RASPBERRY_CLIENTE foreign key (ID_CLIEN) references cliente (ID_CLIENTE) on delete cascade;
	  
alter table arduino add constraint FK_ARDUINO_RASPBERRY foreign key (ID_RASPBE) references raspberry (ID_RASPBERRY) on delete cascade;

alter table componente add constraint FK_COMPONENTE_ARDUINO foreign key (ID_ARD) references arduino (ID_ARDUINO) on delete cascade;

alter table uso add constraint FK_USO_COMPONENTE foreign key (ID_COMP) references componente (ID_COMPONENTE) on delete cascade;

	  